name: Pulumi
description: Deploy an entire Pulumi stack.
inputs:
  stack:
    description: The name of the stack to deploy.
    required: true
  personal-access-token:
    description: A personal access token. Requires `org:admin` scope to manage organizations.
    required: true
  pulumi-access-token:
    description: An access token for the Pulumi App.
    required: true
  gcp-service-account-key:
    description: The contents of a GCP service account JSON key file.
    required: true
runs:
  using: composite
  steps:
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ github.repository_owner }}
        service_account_key: ${{ inputs.gcp_service_account_key }}
        export_default_credentials: true

    - uses: actions/setup-go@v2
      with:
        go-version: "1.16"

    - name: Download Go Module dependencies
      run: go mod download

    - name: Preview planned changes
      uses: pulumi/actions@v3
      with:
        command: preview
        stack-name: dns
      env:
        PULUMI_ACCESS_TOKEN: ${{ inputs.pulumi_access_token }}
        PERSONAL_ACCESS_TOKEN: ${{ inputs.personal_access_token }}

    - name: Apply changes
      uses: pulumi/actions@v3
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      with:
        command: up
        stack-name: dns
        comment-on-pr: true
      env:
        PULUMI_ACCESS_TOKEN: ${{ inputs.pulumi_access_token }}
        PERSONAL_ACCESS_TOKEN: ${{ inputs.personal_access_token }}
