nameOverride: ""
fullnameOverride: ""

services:
  http:
    - name: edge
      host: edge.nicklasfrahm.dev
      backend:
        host: 10.3.11.103.nip.io

    - name: november-registry
      host: registry.november.nicklasfrahm.dev
      backend:
        host: 10.3.11.103.nip.io

    - name: november-dashboard
      host: dashboard.november.nicklasfrahm.dev
      backend:
        host: 10.3.11.103.nip.io

  https:
    - name: edge
      host: edge.nicklasfrahm.dev
      backend:
        host: 10.3.11.103.nip.io

    - name: november-registry
      host: registry.november.nicklasfrahm.dev
      backend:
        host: 10.3.11.103.nip.io

    - name: november-dashboard
      host: dashboard.november.nicklasfrahm.dev
      backend:
        host: 10.3.11.103.nip.io

  kubeapi:
    - name: zebra-k8s
      host: k8s.zebra.nicklasfrahm.dev
      backend:
        host: zebra.srv.nicklasfrahm.dev
