apiVersion: apps/v1
kind: Deployment
metadata:
  name: metal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metal-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metal-api
    spec:
      containers:
        - name: metal-api
          image: ghcr.io/nicklasfrahm/infrastructure-metal:latest
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: metal-api
spec:
  selector:
    app.kubernetes.io/name: metal-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: metal-api
spec:
  parentRefs:
    - name: default
      namespace: default
  hostnames:
    - "alfa.nicklasfrahm.dev"
  rules:
    - backendRefs:
        - name: metal-api
          port: 80
