apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  namespace: blue
  labels:
    app.kubernetes.io/name: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: blue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blue
    spec:
      containers:
      - name: nginx
        image: gcr.io/kuar-demo/kuard-amd64:blue
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: blue
  namespace: blue
  labels:
    app.kubernetes.io/name: blue
spec:
  ports:
  - port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: blue
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blue
  namespace: blue
  labels:
    app.kubernetes.io/name: blue
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prd
spec:
  ingressClassName: traefik
  rules:
  - host: blue.antelope.nicklasfrahm.dev
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: blue
              port:
                number: 80
  tls:
    - secretName: blue-tls
      hosts:
        - blue.antelope.nicklasfrahm.dev
