apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/nicklasfrahm/infrastructure.git
    path: deploy/argocd/root
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
