apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: ISRG Root X1
    email: nicklas.frahm@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production-clusterissuer-key
    solvers:
      - http01:
          ingress:
            class: traefik
