# Version may either be a specific k3s version or a release channel
# as listed here: https://update.k3s.io/v1-release/channels
version: stable

# Cluster provides cluster-wide settings that should be applied
# to all nodes in the cluster. All options are equivalent to the
# commmand line options of the `k3s` command.
cluster:
  server:
    # It is highly recommended to always specify this option as it
    # is used to determine the server URL of the cluster.
    tls-san:
      - deflf02.nicklasfrahm.xyz
    disable:
      - traefik
    snapshotter: native
    flannel-iface: eth0
    cluster-cidr:
      - 10.254.0.0/16
    service-cidr:
      - 10.255.0.0/16
    cluster-dns:
      - 10.255.0.10

# A list of all nodes in the cluster and their connection information.
nodes:
  - role: server
    ssh:
      host: 172.16.2.254
      fingerprint: SHA256:YtaRBa/7wh4xENfF6+7JXoI6liCukw1BdzXSHIQf4fg
      user: nicklasfrahm
      key-file: ~/.ssh/id_ed25519

# An SSH proxy, also known as jumpbox or a bastion host
# can be used to access nodes in a private network.
ssh-proxy:
  host: deflf02.nicklasfrahm.xyz
  user: nicklasfrahm
  key-file: ~/.ssh/id_ed25519
