traefik:
  ingressClass:
    enabled: yes
    isDefaultClass: yes

  service:
    enabled: yes
    type: LoadBalancer

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  ports:
    traefik:
      port: 9000
      expose: no
      exposedPort: 9000
      protocol: TCP
    web:
      port: 8080
      expose: yes
      exposedPort: 80
      protocol: TCP
      redirectTo: websecure
    websecure:
      port: 8443
      expose: yes
      exposedPort: 443
      protocol: TCP
      tls:
        enabled: yes
        options: ""
        certResolver: ""
        domains: []

  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
