{{- range $service := .Values.services.http }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge.fullname" $ }}-http-{{ $service.name }}
  labels:
    {{- include "edge.labels" $ | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ $service.backend.host }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ default 80 $service.backend.port }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "edge.fullname" $ }}-http-{{ $service.name }}
  labels:
    {{- include "edge.labels" $ | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ $service.host }}`)
      services:
        - name: {{ include "edge.fullname" $ }}-http-{{ $service.name }}
          port: 80
{{- end }}
