{{- range $service := .Values.services.http }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "edge.fullname" $ }}-http-{{ $service.name }}
  labels:
    {{- include "edge.labels" $ | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`{{ $service.host }}`)
      services:
        - name: {{ include "edge.fullname" $ }}-http-{{ $service.name }}
          port: 443
  tls:
    passthrough: true
{{- end }}
