{{- range $service := .Values.services.kubeapi }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge.fullname" $ }}-kubeapi-{{ $service.name }}
  labels:
    {{- include "edge.labels" $ | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ $service.backend.host }}
  ports:
    - name: https
      protocol: TCP
      port: 6443
      targetPort: {{ default 6443 $service.backend.port }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "edge.fullname" $ }}-kubeapi-{{ $service.name }}
  labels:
    {{- include "edge.labels" $ | nindent 4 }}
spec:
  entryPoints:
    - kubeapi
  routes:
    - match: HostSNI(`{{ $service.host }}`)
      services:
        - name: {{ include "edge.fullname" $ }}-kubeapi-{{ $service.name }}
          port: 6443
  tls:
    passthrough: true
{{- end }}
