{{- range $service := .Values.services.http }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge.fullname" $ }}-http-{{ $service.name }}
  labels:
    {{- include "edge.labels" $ | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ $service.backend.host }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
{{- end }}
