zones:
  - provider: cloudflare
    name: nicklasfrahm.dev
    records:
      - name: "@"
        type: GITHUB_PAGES
        githubPages:
          org: nicklasfrahm
      - name: kubestack
        type: GITHUB_PAGES
        githubPages:
          org: nicklasfrahm
      - name: dktil01
        type: SITE
        site:
          router: alfa.nicklasfrahm.dev
      - name: deflf01
        type: SITE
        site:
          router: bravo.nicklasfrahm.dev
      - name: deflf02
        type: SITE
        site:
          router: charlie.nicklasfrahm.dev
      - name: dksjb00
        type: SITE
        site:
          router: delta.nicklasfrahm.dev
      - name: dksjb01
        type: SITE
        site:
          router: delta.nicklasfrahm.dev
      - name: dksjb02
        type: SITE
        site:
          router: delta.nicklasfrahm.dev
      - name: moos
        type: SITE
        site:
          router: delta.nicklasfrahm.dev

  - provider: cloudflare
    name: odance.dk
    records: []

  - provider: cloudflare
    name: odance.nl
    records: []
