zones:
  - provider: cloudflare
    name: nicklasfrahm.dev
    records:
      - name: gitops
        type: CNAME
        values:
          - delta.nicklasfrahm.dev
      - name: api
        type: CNAME
        values:
          - delta.nicklasfrahm.dev
      - name: mc-survival
        type: CNAME
        values:
          - delta.nicklasfrahm.dev
      - name: "@"
        type: GITHUB_PAGES
        githubPages:
          org: nicklasfrahm-dev
      - name: kraut
        type: GITHUB_PAGES
        githubPages:
          org: nicklasfrahm
      - name: cloud
        type: GITHUB_PAGES
        githubPages:
          org: nicklasfrahm
      # TODO: Add "kubeapi" listener to edge before routing traffic to "alfa".
      - name: november
        type: SITE
        site:
          router: delta.nicklasfrahm.dev
      - name: moos
        type: SITE
        site:
          router: delta.nicklasfrahm.dev
      # A single node cluster with some storage to host MinIO for backups.
      - name: mon0
        type: SITE
        site:
          router: alfa.nicklasfrahm.dev
      - name: zebra
        type: SITE
        site:
          router: alfa.nicklasfrahm.dev
      # My observability stack.
      - name: grafana
        type: SITE
        site:
          router: zebra.nicklasfrahm.dev
      - name: insights
        type: CNAME
        values:
          - mon0.nicklasfrahm.dev
