zones:
  - provider: cloudflare
    name: nicklasfrahm.dev
    records:
      - name: gitops
        type: CNAME
        values:
          - alfa.nicklasfrahm.dev
      - name: api
        type: CNAME
        values:
          - alfa.nicklasfrahm.dev
      - name: mc-survival
        type: CNAME
        values:
          - delta.nicklasfrahm.dev
      - name: "@"
        type: GITHUB_PAGES
        githubPages:
          org: nicklasfrahm
      - name: kubestack
        type: GITHUB_PAGES
        githubPages:
          org: nicklasfrahm
      # TODO: Add "kubeapi" listener to edge before routing traffic to "alfa".
      - name: november
        type: SITE
        site:
          router: delta.nicklasfrahm.dev
      - name: moos
        type: SITE
        site:
          router: delta.nicklasfrahm.dev

  - provider: cloudflare
    name: odance.nl
    records:
      - name: "@"
        type: CNAME
        values:
          - delta.nicklasfrahm.dev
