configs:
  params:
    server.insecure: yes
  cm:
    url: "https://gitops.${INGRESS_DOMAIN}"
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: ${OAUTH_CLIENT_ID}
            clientSecret: ${OAUTH_CLIENT_SECRET}
            orgs:
              - name: nicklasfrahm-dev
            teamNameField: slug
    admin.enabled: "false"
  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, nicklasfrahm-dev:argocd-admins, role:admin
    scopes: "[groups, email]"

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - "gitops.${INGRESS_DOMAIN}"
    tls:
      - secretName: argocd-tls
        hosts:
          - "gitops.${INGRESS_DOMAIN}"
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi

redis:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

repoServer:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

controller:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

dex:
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

notifications:
  enabled: false

applicationSet:
  enabled: false
