cluster:
  name: "${ROUTER}"

operator:
  # This is only needed when running on a single node.
  replicas: 1

kubeProxyReplacement: "true"

# This is needed to allow cilium to reliably connect
# to the Kubernetes API without hardcoding IPs.
k8sServiceHost: "${ROUTER}.nicklasfrahm.dev"
k8sServicePort: 7443

ipam:
  operator:
    # This is needed to prevent cilium from picking "10.0.0.0/8"
    # as the pod CIDR (which is an insane default).
    clusterPoolIPv4PodCIDRList:
      - "172.28.0.0/16"

gatewayAPI:
  # This requires the Gateway APIs to be installed prior to installing cilium.
  enabled: true

# TODO: Fix this.
# https://github.com/cilium/cilium/blob/103077d3ecf826b9329a02f7c0c0db8190452fe7/install/kubernetes/cilium/templates/cilium-configmap.yaml#L704
# nodePort:
#   # Prevent cilium from getting confused which interface is the WAN and which is the LAN.
#   directRoutingDevice: lo
# Prevent the cilium-agent from being confused between the WAN and the LAN interface.
# devices:
#   - lo
#   - enp2s0
# enableRuntimeDeviceDetection: true
