traefik:
  ingressClass:
    enabled: yes
    isDefaultClass: yes

  service:
    enabled: yes
    type: LoadBalancer

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    metrics:
      - type: Resource
        resource:
          name: memory
          targetAverageUtilization: 75
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 75

  ports:
    traefik:
      port: 9000
      expose: no
      exposedPort: 9000
      protocol: TCP
    web:
      port: 8080
      expose: yes
      exposedPort: 80
      nodePort: 30080
      protocol: TCP
      redirectTo: websecure
    websecure:
      port: 8443
      expose: yes
      exposedPort: 443
      nodePort: 30443
      protocol: TCP
      tls:
        enabled: yes

  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
