ingressClass:
  enabled: yes
  isDefaultClass: yes

service:
  enabled: yes
  type: LoadBalancer
  single: false

resources:
  requests:
    cpu: 128m
    memory: 256Mi
  limits:
    cpu: 128m
    memory: 256Mi

ports:
  traefik:
    port: 9000
    expose: no
    exposedPort: 9000
    protocol: TCP
  web:
    port: 8080
    expose: yes
    exposedPort: 80
    nodePort: 30080
    protocol: TCP
  websecure:
    port: 8443
    expose: yes
    exposedPort: 443
    nodePort: 30443
    protocol: TCP
    tls:
      enabled: yes

providers:
  kubernetesIngress:
    publishedService:
      enabled: true
