apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusterissuers
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/nicklasfrahm/infrastructure.git
    targetRevision: HEAD
    path: deploy/kubectl/clusterissuers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
