---
apiVersion: v1
kind: Namespace
metadata:
  name: ddclient
---
apiVersion: v1
kind: Secret
metadata:
  name: ddclient-config
  namespace: ddclient
  labels:
    app: ddclient
stringData:
  ddclient.conf: |
    daemon=300
    syslog=yes
    protocol=dyndns2
    use=cmd, cmd='curl https://checkipv4.dedyn.io/'
    ssl=yes
    server=update.dedyn.io
    login=${DDCLIENT_DOMAIN}
    password='${DDCLIENT_TOKEN}'
    ${DDCLIENT_DOMAIN}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddclient-deployment
  namespace: ddclient
  labels:
    app: ddclient
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: ddclient
  template:
    metadata:
      labels:
        app: ddclient
    spec:
      volumes:
        - name: ddclient-config
          secret:
            secretName: ddclient-config
      containers:
        - name: ddclient
          image: linuxserver/ddclient
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /config
              name: ddclient-config
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 128Mi
