apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://tph99.nicklasfrahm.xyz:6443
    namespace: argo-cd
  project: default
  source:
    path: charts/apps
    repoURL: https://github.com/nicklasfrahm/infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
