{{- range .Values.clusters }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-{{ .name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://{{ .name }}.nicklasfrahm.xyz:6443
    namespace: cert-manager
  project: default
  source:
    path: charts/cert-manager
    repoURL: https://github.com/nicklasfrahm/infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
