apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: traefik
spec:
  generators:
    - clusters:
        # Only target remote clusters.
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: traefik
    spec:
      destination:
        server: "{{server}}" # 'server' field of the secret
        namespace: traefik
      project: default
      source:
        path: charts/traefik
        repoURL: https://github.com/nicklasfrahm/infrastructure.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
