argo-cd:
  dex:
    enabled: true
  server:
    extraArgs:
      - --insecure
    config:
      url: https://argo-cd.nicklasfrahm.xyz
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: 1435c46d92d31759da03
              clientSecret: $github-oauth:dex.github.clientSecret
              orgs:
                - name: nicklasfrahm-xyz
              teamNameField: slug
      admin.enabled: "false"
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, nicklasfrahm-xyz:argonauts, role:admin
      scopes: "[groups, email]"
    ingress:
      enabled: true
      ingressClassName: traefik-tph99
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - argo-cd.nicklasfrahm.xyz
      tls:
        - secretName: argocd-tls
          hosts:
            - argo-cd.nicklasfrahm.xyz
