argo-cd:
  dex:
    enabled: true
  server:
    extraArgs:
      - --insecure
    config:
      url: https://argo-cd.nicklasfrahm.xyz
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: 1435c46d92d31759da03
              clientSecret: $github-oauth:dex.github.clientSecret
              orgs:
                - name: nicklasfrahm-xyz
      policy.default: role.readonly
      policy.csv: |
        g, nicklasfrahm-xyz, role:admin
