apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ExternalName
  externalName: nginx.10.3.11.103.nip.io
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  - port: 443
    protocol: TCP
    targetPort: 443
    name: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
  - host: edge.nicklasfrahm.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: nginx
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`edge.nicklasfrahm.dev`)
      services:
        - name: nginx
          port: 443
  tls:
    passthrough: true
