apiVersion: v1
kind: Namespace
metadata:
  name: site-system
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  namespace: site-system
stringData:
  gcp.json: ${GCP_SITE_CREDENTIALS}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dnsctl
  namespace: site-system
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dnsctl
              image: ghcr.io/nicklasfrahm/dnsctl
              args:
                - ${SITE_FQDN}
          # TODO: Add volume and modify volue permissions.
