apiVersion: v2
name: o11y-ui
description: The UI for an observability platform.
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: grafana
    version: 7.3.3
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
