apiVersion: v2
name: cert-manager
description: An umbrella chart to configure cert-manager.
version: 1.9.1
dependencies:
  - name: cert-manager
    version: 1.9.1
    repository: https://charts.jetstack.io
