# TODO: Set up authentication.

victoria-metrics-single:
  enabled: true
  server:
    ingress:
      enabled: true
      hosts:
        - name: "victoria-metrics.10.0.11.33.nip.io"
          path: "/"
          port: http
