apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odance-wordpress-https-redirect
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: odance-prd-https-redirect@kubernetescrd
spec:
  rules:
    - host: odance.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: odance-wordpress
                port:
                  number: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
