name: Pulumi

on:
  workflow_dispatch:
  schedule:
    - cron: "45 5 * * *"
  push:
    branches:
      - main
    paths:
      - .github/workflows/pulumi.yml
      - deploy/**
      - pkg/**
      - Pulumi.*
      - go.*
  pull_request:
    branches:
      - main

jobs:
  pulumi:
    name: Pulumi
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack:
          - foundation
    environment:
      name: ${{ matrix.stack }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: stable

      - name: Download dependencies
        run: go mod download

      - name: Preview infrastructure
        uses: pulumi/actions@v3
        if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
        with:
          command: preview
          stack-name: ${{ matrix.stack }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Update infrastructure
        uses: pulumi/actions@v3
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        with:
          command: preview
          stack-name: ${{ matrix.stack }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

