name: SSH

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  kubernetes:
    name: Kubernetes
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        site:
          - ger-flb-bl8
          - den-sdb-osg18
    environment:
      name: ${{ matrix.site }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Deploy k3s via proxy host
        uses: appleboy/ssh-action@master
        if: secrets.SSH_PROXY_HOST != ''
        with:
          script_stop: true
          proxy_host: ${{ secrets.SSH_PROXY_HOST }}
          proxy_fingerprint: ${{ secrets.SSH_PROXY_FINGERPRINT }}
          proxy_username: ${{ secrets.SSH_PROXY_USER }}
          proxy_key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_TARGET_HOST }}
          fingerprint: ${{ secrets.SSH_TARGET_FINGERPRINT }}
          username: ${{ secrets.SSH_TARGET_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            curl -sfL https://get.k3s.io | sudo sh -s - \
              --advertise-address $(host -t a ${{ secrets.SITE_FQDN }} | cut -d ' ' -f4) \
              --tls-san ${{ secrets.SITE_FQDN }} \
              --disable traefik \
              --write-kubeconfig-mode 644 \
              --selinux
            mkdir -p -m 700 .kube
            sudo cp -f /etc/rancher/k3s/k3s.yaml .kube/config
            sudo chown ${{ secrets.SSH_TARGET_USER }}:${{ secrets.SSH_TARGET_USER }} .kube/config
            sudo chmod 600 .kube/config

      - name: Deploy k3s
        uses: appleboy/ssh-action@master
        if: secrets.SSH_PROXY_HOST == ''
        with:
          script_stop: true
          host: ${{ secrets.SSH_TARGET_HOST }}
          fingerprint: ${{ secrets.SSH_TARGET_FINGERPRINT }}
          username: ${{ secrets.SSH_TARGET_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            curl -sfL https://get.k3s.io | sudo sh -s - \
              --advertise-address $(host -t a ${{ secrets.SITE_FQDN }} | cut -d ' ' -f4) \
              --tls-san ${{ secrets.SITE_FQDN }} \
              --disable traefik \
              --write-kubeconfig-mode 644 \
              --selinux
            mkdir -p -m 700 .kube
            sudo cp -f /etc/rancher/k3s/k3s.yaml .kube/config
            sudo chown ${{ secrets.SSH_TARGET_USER }}:${{ secrets.SSH_TARGET_USER }} .kube/config
            sudo chmod 600 .kube/config

      - name: Download kubeconfig via proxy host
        uses: nicklasfrahm/scp-action@main
        if: secrets.SSH_PROXY_HOST != ''
        with:
          direction: download
          proxy_host: ${{ secrets.SSH_PROXY_HOST }}
          proxy_fingerprint: ${{ secrets.SSH_PROXY_FINGERPRINT }}
          proxy_username: ${{ secrets.SSH_PROXY_USER }}
          proxy_key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_TARGET_HOST }}
          fingerprint: ${{ secrets.SSH_TARGET_FINGERPRINT }}
          username: ${{ secrets.SSH_TARGET_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: /etc/rancher/k3s/k3s.yaml
          target: kubeconfig.yml

      - name: Download kubeconfig
        uses: nicklasfrahm/scp-action@main
        if: secrets.SSH_PROXY_HOST == ''
        with:
          direction: download
          host: ${{ secrets.SSH_TARGET_HOST }}
          fingerprint: ${{ secrets.SSH_TARGET_FINGERPRINT }}
          username: ${{ secrets.SSH_TARGET_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: /etc/rancher/k3s/k3s.yaml
          target: kubeconfig.yml

      - name: Adjust API server URL
        run: sed -i s/127.0.0.1/${{ secrets.SITE_FQDN }}/g kubeconfig.yml

      - name: Create secret for kubeconfig
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
          gh secret set KUBECONFIG -r ${{ github.repository }} -e ${{ matrix.site }} < kubeconfig.yml
