name: Tools

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - .github/workflows/tools.yml

jobs:
  binaries:
    name: Binaries
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/arm
          - darwin/amd64
          - windows/amd64
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Go compiler
        uses: actions/setup-go@v2
        with:
          check-latest: true

      - name: Build binaries
        run: UPX=-9 PLATFORM=${{ matrix.platform }} make build

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: bin/*
