apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: argocd-tls
  dnsNames:
    - argo-cd.nicklasfrahm.xyz
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
